Ansible: Greatly simplify setup script
Existing script tried to be too cheeky and was flaky across MacOS versions. New
version installs Homebrew from the upstream installer (which takes care of
Xcode CLI Tools for us), installs Ansible from that, then proceeds. No magic
around playbook detection either.

diff --git a/ansible/run b/ansible/run
--- a/ansible/run
+++ b/ansible/run
@@ -10,52 +10,32 @@ argv=( ${argv:#--(check|verbose)} )
 argv=( ${argv:#-([Cv])##} )
 
 verbosity=${#verbose}
-if (( verbosity == 3 )) setopt verbose
-if (( verbosity >= 4 )) setopt xtrace
-
-TMP_ANSIBLE_DIR='/tmp/dotfiles_portable_ansible'
-XCODE_CLT_DIR='/Library/Developer/CommandLineTools'
+if (( verbosity >= 4 )) setopt verbose
+if (( verbosity >= 5 )) setopt xtrace
 
 abort() {
   print "$1" >&2
   exit 1
 }
 
-# Dependency setup
-install_xcode_clt() {
-  print "Xcode command line tools needed. Launching installer..."
-  xcode-select --install || return 1
-  print -n "Press <Return> when finished."
-  read -s
-  [[ -d $XCODE_CLT_DIR ]]
+install_homebrew() {
+  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
 }
 
-install_ansible() {
-  print "Ansible not found, installing into temporary virtualenv..."
-  setopt localoptions err_return
-  
-  local pyenv=$TMP_ANSIBLE_DIR
-  mkdir -p $pyenv/{venv-module,venv}
-  
-  # Virtualenv is not present in the Xcode CLI tools, so we must install it
-  # before we can set up the venv. Install to a temporary location to avoid
-  # conflict with any other existing Python packages on the system.
-  /usr/bin/python3 -m pip install --target $pyenv/venv-module virtualenv
-  
-  # Bootstrap a virtualenv for the Ansible install
-  env PYTHONPATH="$pyenv/venv-module" $pyenv/venv-module/bin/virtualenv $pyenv/venv
-  # NOTE: Implicit dependency on `path` being set first. See below.
-  source $pyenv/venv/bin/activate
-  
-  # Ansible will require an updated setuptools and pip to build/install, so 
-  # install upgraded copies of those one-by-one first.
-  local p
-  for p in pip setuptools ansible;
-    pip install --upgrade $p
+check_homebrew() {
+  local brew_install brew_bin
+  case $(arch) in
+    arm64) brew_install=/opt/homebrew ;;
+    i386)  brew_install=/usr/local/Homebrew ;;
+  esac
+  brew_bin=$brew_install/bin/brew
+  if [[ ! -d $brew_install || ! -x $brew_bin ]]; then
+    install_homebrew
+  fi
 }
 
 need_become_pass() {
-  local p f
+  local p
   for p in "$@";
     [[ $(cat $p) =~ "(become:[[:space:]]*([Yy]|[Tt]|[Oo][Nn])|ansible_become_password)" ]] &&
       return 0
@@ -63,16 +43,16 @@ need_become_pass() {
 }
 
 get_sudo_pass() {
+  need_become_pass "$@" || return
   print -n "Enter your password for sudo: "
   read -rs sudo_password
 }
 
-# Set up environment
-# Ensure our PATH is sane, and includes Homebrew + our temporary bin 
-# directories, as Ansible modules will attempt to search these for things we 
-# need like 'brew' and 'mas' and our portable Ansible.
+check_homebrew || abort "unable to install Homebrew"
+
+# If Homebrew was just installed, PATH may not contain its bin dir
 path=(
-  /opt/homebrew/bin
+  /opt/homebrew/bin(N)
   /usr/local/bin
   /tmp/dotfiles_portable_ansible/venv/bin(N)
   /usr/bin
@@ -81,77 +61,17 @@ path=(
   /sbin
 )
 
-# Check pre-requisites
-if [[ ! -d $XCODE_CLT_DIR ]]; then
-  install_xcode_clt ||
-    abort "failed to install Xcode Command Line Tools"
-fi
-
 if (( ! $+commands[ansible-playbook] )); then
-  install_ansible ||
-    abort "failed to install Ansible"
+  brew "ansible" || abort "unable to install Ansible"
 fi
 
-# Search for playbooks to run based on arguments
-# Searches in order:
-# - Path to Yaml file.
-# - Name of a stage (ie 01-system), with or without leading digit+hyphen,
-#   matching all executable Yaml files inside.
-# - Name of a target (ie 10-install-rosetta), with or without leading
-#   digit+hyphen, without trailing Yaml extension, searching all stages for a 
-#   single matching Yaml file.
-# - Defaults to all Yaml files in all stages, in lexographical order, if none
-#   is given.
-# Removes duplicate playbooks.
-typeset -a playbooks
-() {
-  local basedir=${0:h}
-  local targets=( "$@" )
-  # If no arguments given, then search for all stage folders,
-  if (( ! ${#targets} )) targets=( [[:digit:]][[:digit:]]-*(-/N) )
-  # No stage folders found?,
-  if (( ! ${#targets} )) abort "no playbooks to run"
-  
-  local item try
-  for item in $targets; do
-    if [[ $item == *.((#i)y(a|)ml) && -e $item ]]; then
-      playbooks+=( $item )
-      continue
-    fi
-    
-    if [[ $item == ([[:digit:]][[:digit:]]-|)(*) ]]; then
-      # Is it a stage name? Ie, 01-system
-      if [[ -d $basedir/([[:digit:]][[:digit:]]-|)$item(#q-N) ]]; then
-        playbooks+=( $basedir/([[:digit:]][[:digit:]]-|)$item/(*)((#i).y(a|)ml)(-.Ne:'[[ -x $REPLY ]]':) )
-        continue
-      fi
-      
-      # Is it a target name we need to search for inside a stage?
-      try=( $basedir/[[:digit:]][[:digit:]]-*/([[:digit:]][[:digit:]]-|)$item((#i).y(a|)ml)(-.N) )
-      # Does a target by this name exists in more than one place?,
-      if (( ${#try} > 1 )) abort "ambiguous target name: $item"
-      if [[ -e $try ]]; then
-        playbooks+=( $try )
-        continue
-      fi
-    fi
-    
-    abort "could not locate target: $item"
-  done
-  
-  # Remove duplicates
-  playbooks=( ${(u)playbooks} )
-} "$@"
+get_sudo_pass "$@"
 
-# Do we need a sudo password for the playbooks we're running?
-need_become_pass $playbooks &&
-  get_sudo_pass
-
-env ANSIBLE_FORCE_COLOR=1 ansible-playbook \
+ansible-playbook \
   ${verbose:+-${(pl[$verbosity][v])}} \
   ${check:+--check} \
   ${=sudo_password:+"-e ansible_become_password=$sudo_password"} \
-  $playbooks |& {
+  "$@" |& {
     (( verbosity > 0 )) &&
       tee "${0:h}/log/$(date +%s).log" ||
       cat
